### PR TITLE
DataCutter-related fixes for multiclass

### LINKED ISSUE #245: Labels may not be dropped in MultiClassClassification
**Describe the bug**
Dropping the long tail of low cardinality labels is currently performed DataCutter.prepare. There are multiple call paths and we see it skipped in production. This results in performance degradation or even pipeline failures violating various constraints in MLlib such as 
- 100 label limit in Classifier
- "dense matrix too large"

**To Reproduce**
internal pipeline, failing to reproduce in unit tests yet

**Expected behavior**
an easier way to reason that DataCutter is not bypassed.

**Logs or screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by gerashegalov**
**Related issues**
Fixes #245

- label sort by count is nondeterministic for labels with the same count
- data cutter label trimming in validation is not called prior to bestEstimator
- column  metadata is not updated after trimming
- in `DataCutter.estimate` whereas `filter` before `sort` is good for performance it may not drop labels non-deterministically unlike filtering over a stable order. 
  
**Describe the proposed solution**
Remove non-determinism

### CODE REVIEW

**Comment by tovbinm** [comment]
@gerashegalov can you elaborate more on the proposed fixes? thanks.

**Comment by gerashegalov** [comment]
@tovbinm there are multiple issues.

One is the sort stability when there are multiple top labels with identical cardinality. We can solve this by adding the label as a secondary sort key. Similar issue with filtering labels for the minFraction prior to sorting. And #251 caused the data cutter omission to begin with

File: core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala [hunk 1]
```diff
@@ -121,25 +166,30 @@ class DataCutter(uid: String = UID[DataCutter]) extends Splitter(uid = uid) with
...
       .filter(r => (r.getLong(1) / totalValues) >= minLabelFract)
-      .sort(col(colCount).desc)
       .take(maxLabels)
       .map(_.getDouble(0))
 
     val labelSet = labelsKeep.toSet
-    val labelsDropped = labelCounts.filter(r => !labelSet.contains(r.getDouble(0))).collect().map(_.getDouble(0)).toSet
+    val labelsDropped = labelCounts
+      .filter(r => !labelSet.contains(r.getDouble(0)))
+      .take(100)
```
Comment (leahmcguire) [inline core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala]: maybe instead of just keeping the first hundred dropped labels we should just keep a count of how many we dropped

File: core/src/main/scala/com/salesforce/op/stages/impl/selector/ModelSelector.scala [hunk 2]
```diff
@@ -138,16 +137,19 @@ E <: Estimator[_] with OpPipelineStage2[RealNN, OPVector, Prediction]]
...
           .withColumn(ModelSelectorNames.idColName, monotonically_increasing_id())
       }
-    require(!datasetWithID.isEmpty, "Dataset cannot be empty")
+    require(!datasetWithIDPre.isEmpty, "Dataset cannot be empty")
 
-    val splitterSummary = splitter.flatMap(_.preValidationPrepare(datasetWithID))
+    val splitterSummary = splitter.flatMap(_.preValidationPrepare(datasetWithIDPre))
+    val datasetWithID = splitter.collect {
+      case dc: DataCutter => dc.validationPrepare(datasetWithIDPre)
+    }.getOrElse(datasetWithIDPre)
```
Comment (leahmcguire) [inline core/src/main/scala/com/salesforce/op/stages/impl/selector/ModelSelector.scala]: if you want to avoid the match on case for the data prepare we could modify the return type of  preValidationPrepare to optionally return a dataset. then the data cutter preValidationPrepare could cut the data and the validationPrepare could just return the dataset unchanged...

File: core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala (hunk 1 above)
Comment (gerashegalov) [reply core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala]: Good idea. We could also do both: number of dropped labels and the topK of them for some low K, so we can log it `dropped label1, label3, label10 ...`

File: core/src/main/scala/com/salesforce/op/stages/impl/selector/ModelSelector.scala (hunk 2 above)
Comment (gerashegalov) [reply core/src/main/scala/com/salesforce/op/stages/impl/selector/ModelSelector.scala]: yes. hacked something together to see if it's generally a good approach

**Comment by tovbinm** [comment]
@gerashegalov please let us know when you want the PR reviewed.

**Comment by gerashegalov** [comment]
@tovbinm it's ready

File: core/src/main/scala/com/salesforce/op/stages/impl/selector/ModelSelector.scala [hunk 3]
```diff
@@ -156,7 +158,11 @@ E <: Estimator[_] with OpPipelineStage2[RealNN, OPVector, Prediction]]
       best
     }
 
-    val preparedData = splitter.map(_.validationPrepare(datasetWithID)).getOrElse(datasetWithID)
+    val preparedData = splitter.collect {
```
Comment (tovbinm) [inline core/src/main/scala/com/salesforce/op/stages/impl/selector/ModelSelector.scala]: I find this part quite confusing. We apply `validationPrepare` only if it's a `DataCutter`, and then only if it's not `DataCutter` we apply `validationPrepare`. So what I get from this is that when it's a `DataCutter` we want to apply `validationPrepare` early, but not for any other splitter types. Perhaps it's worth adding a few lines of docs explaining why.

File: core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala [hunk 4]
```diff
@@ -86,16 +89,37 @@ class DataCutter(uid: String = UID[DataCutter]) extends Splitter(uid = uid) with
...
   }
 
+
+  private def getLabelsFromMetadata(data: DataFrame): Array[String] =
+    Try {
+      val labelSF = data.schema.head
+      val labelColMetadata = labelSF.metadata
+      log.info(s"Raw label column metadata: $labelColMetadata")
+      labelColMetadata
+        .getMetadata("ml_attr")
```
Comment (tovbinm) [inline core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala]: object `org.apache.spark.ml.attribute.AttributeKeys` has these consts defined. please use those if possible.

File: core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala [hunk 5]
```diff
@@ -86,16 +89,37 @@ class DataCutter(uid: String = UID[DataCutter]) extends Splitter(uid = uid) with
 
     import data.sparkSession.implicits._
 
-    val labels = data.map(r => r.getDouble(0) -> 1L)
-    val labelCounts = labels.groupBy(labels.columns(0)).sum(labels.columns(1)).persist()
-    val (resKeep, resDrop) = estimate(labelCounts)
+    val labels = data.map(r => r.getDouble(0))
+    val labelCounts = labels.groupBy(labels.columns(0)).count().persist()
```
Comment (tovbinm) [inline core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala]: `.count().persist()` seems weird to me. what's the return type of `count()`?

File: core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala [hunk 6]
```diff
@@ -86,16 +89,37 @@ class DataCutter(uid: String = UID[DataCutter]) extends Splitter(uid = uid) with
...
+    val res = estimate(labelCounts)
     labelCounts.unpersist()
-    setLabels(resKeep, resDrop)
+    setLabels(res.labelsKept.toSet, res.labelsDropped.toSet, res.labelsDroppedTotal)
```
Comment (tovbinm) [inline core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala]: `.distinct` perhaps instead of `.toSet` so the order would be kept?

File: core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala [hunk 7]
```diff
@@ -104,11 +128,35 @@ class DataCutter(uid: String = UID[DataCutter]) extends Splitter(uid = uid) with
...
+      dataPrep
+    } else {
+      log.info(s"Dropping rows with columns not in $labelSet")
+      val labelColName = dataPrep.columns(0)
+
+      val na = NominalAttribute.defaultAttr.withName(labelColName)
+      val metadataNA = if (labelMetaArr.isEmpty) {
+        na.withNumValues(labelSet.size)
+      } else {
+        // trim the metadata
```
Comment (tovbinm) [inline core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala]: what does `trim the metadata` and `trim the dataframe` means? please add more explanations  ;)

File: core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala [hunk 8]
```diff
@@ -117,29 +165,48 @@ class DataCutter(uid: String = UID[DataCutter]) extends Splitter(uid = uid) with
    * @param labelCounts
    * @return Set of labels to keep & to drop
    */
-  private[op] def estimate(labelCounts: DataFrame): (Set[Double], Set[Double]) = {
+  private[op] def estimate(labelCounts: DataFrame): DataCutterSummary = {
+    val numDroppedToRecord = 10
```
Comment (tovbinm) [inline core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala]: why magic number 10? dont you want this configurable?

File: core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala (hunk 4 above)
Comment (gerashegalov) [reply core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala]: considered it but it's a package-private class in `org.apache.spark.ml.attribute`

File: core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala (hunk 5 above)
Comment (gerashegalov) [reply core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala]: accidental leftover, did not remove enough stuff after getting rid of an unnecessary transformation `r.getDouble(0) -> 1L)`

Comment (gerashegalov) [reply core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala]: UPDATE: sorry, I got confused it belongs here for the same reason as before since we produce a df with `(label, count)` per [scaladoc](https://spark.apache.org/docs/2.2.0/api/scala/index.html#org.apache.spark.sql.RelationalGroupedDataset@count():org.apache.spark.sql.DataFrame)

File: core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala (hunk 6 above)
Comment (gerashegalov) [reply core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala]: good idea, toSet is the current behavior

**Comment by gerashegalov** [comment]
not ready for review yet, checkpointing WIP,  sorting out test issues.

File: core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala [hunk 9]
```diff
@@ -82,33 +85,95 @@ class DataCutter(uid: String = UID[DataCutter]) extends Splitter(uid = uid) with
...
+        case dcs: DataCutterSummary if dcs.preparedDF.isDefined => dcs
+      }
+      .getOrElse {
+        val labelMetaArr = getLabelsFromMetadata(data)
+        val labelSet = getLabelsToKeep.toSet
+
+        // discount unseen label
+        val integralLabelSet = 0.until(labelMetaArr.length - 1)
+          .map(_.toDouble)
+          .toSet
```
Comment (leahmcguire) [inline core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala]: I dont think you can convert this to a set - it is a sequence where the name is matched to the value by the index

Comment (gerashegalov) [reply core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala]: you are right Leah. I am also just getting rid of it because it was my old way to prevent multiple executions of trimming, which we now handle more explicitly

File: core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala [hunk 10]
```diff
@@ -82,33 +85,87 @@ class DataCutter(uid: String = UID[DataCutter]) extends Splitter(uid = uid) with
...
-    import data.sparkSession.implicits._
-
-    val labels = data.map(r => r.getDouble(0) -> 1L)
-    val labelCounts = labels.groupBy(labels.columns(0)).sum(labels.columns(1)).persist()
-    val (resKeep, resDrop) = estimate(labelCounts)
-    labelCounts.unpersist()
-    setLabels(resKeep, resDrop)
+  override def preValidationPrepare(data: Dataset[Row], labelColNameOpt: Option[String]): Option[SplitterSummary] = {
+    val labelColName = labelColNameOpt.getOrElse(data.columns(0))
+    val labelColIdx = data.columns.indexOf(labelColName)
```
Comment (leahmcguire) [inline core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala]: I wouldnt assume that the first column is the label - that is the problem you had in the first place. Make a spark parameter on the base class where you set the name of the label column

File: core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala [hunk 11]
```diff
@@ -82,33 +85,87 @@ class DataCutter(uid: String = UID[DataCutter]) extends Splitter(uid = uid) with
...
+
+    if (Try(getLabelsToKeep).toOption.isEmpty) {
```
Comment (leahmcguire) [inline core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala]: this is a spark parameter just use isSet

File: core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala [hunk 12]
```diff
@@ -82,33 +85,87 @@ class DataCutter(uid: String = UID[DataCutter]) extends Splitter(uid = uid) with
...
+        val dataPrep = {
+          log.info(s"Dropping rows with columns not in $labelSet")
+
+          // Update metadata that spark.ml Classifier is using tp determine the number of classes
+          //
+          val na = NominalAttribute.defaultAttr.withName(labelColName)
+          val metadataNA = if (labelMetaArr.isEmpty) {
+            na
+          } else {
+            na.withValues(labelMetaArr.take(labelSet.size))
```
Comment (leahmcguire) [inline core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala]: I think part of the problem may be the assumption that the first labels are the ones that you keep (they should be but there are probably edge cases where it is not true). `labelMetaArr.zipWithIndex.filter{(case (_, i))labelSet.contains(i)}`

File: core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala [hunk 13]
```diff
@@ -82,33 +85,87 @@ class DataCutter(uid: String = UID[DataCutter]) extends Splitter(uid = uid) with
...
+            .withColumn(labelColName, data
+              .col(labelColName)
+              .as("_", metadataNA.toMetadata))
+        }
+
+        DataCutterSummary(
+          labelsKept = getLabelsToKeep,
+          labelsDropped = getLabelsToDrop,
+          labelsDroppedTotal = getLabelsDroppedTotal,
+          preparedDF = Option(dataPrep)
```
Comment (leahmcguire) [inline core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala]: We should not be putting the preparedDataFrame into the summary

File: core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala (hunk 10 above)
Comment (gerashegalov) [reply core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala]: you == current version? it's now a method parameter (which I could make a DC param).

File: core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala (hunk 12 above)
Comment (gerashegalov) [reply core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala]: agreed, more robust and elegant

File: core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala (hunk 10 above)
Comment (leahmcguire) [reply core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala]: I thought the rearranging of the dataframe was to solve this ordering assumption...

**Comment by gerashegalov** [comment]
marking as ready for review since all unit testing are passing

File: core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala [hunk 14]
```diff
@@ -75,40 +78,91 @@ class DataCutter(uid: String = UID[DataCutter]) extends Splitter(uid = uid) with
...
+
+    summary = Option(DataCutterSummary(
+      labelsKept = getLabelsToKeep,
+      labelsDropped = getLabelsToDrop,
+      labelsDroppedTotal = getLabelsDroppedTotal
+    ))
+
+    if (isSet(cacheValidatedDFForTesting) && $(cacheValidatedDFForTesting)) {
+      cachedDataFrameForTesting = Option(dataPrep)
+    }
```
Comment (leahmcguire) [inline core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala]: should we remove this before we merge?

File: core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala [hunk 15]
```diff
@@ -75,40 +78,91 @@ class DataCutter(uid: String = UID[DataCutter]) extends Splitter(uid = uid) with
...
+    log.info(s"Raw label column metadata: $labelColMetadata")
 
-    dataUse
+    Try {
+      labelColMetadata
+        .getMetadata("ml_attr")
+        .getStringArray("vals")
+    }
+    .recover { case nonFatal =>
+      log.warn("Recovering non-fatal exception using num_vals", nonFatal)
```
Comment (leahmcguire) [inline core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala]: I dont understand these exceptions

File: core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala (hunk 14 above)
Comment (gerashegalov) [reply core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala]: it would be good to keep the functionality to prevent regressions in the future way. I suppose it would be more elegant to have a TestDataCutter extending DataCutter with the sole purpose of intercepting the result dataframe.

File: core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala (hunk 15 above)
Comment (gerashegalov) [reply core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala]: I wanted to avoid too elaborate of the logic for checking whether these attributes are set and set correctly. The most common case is NoSuchKey when the attributes are not there.

File: core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataBalancer.scala [hunk 16]
```diff
@@ -181,6 +178,22 @@ class DataBalancer(uid: String = UID[DataBalancer]) extends Splitter(uid = uid)
     balanced.persist()
   }
 
+  private def splitNegativePositive(data: Dataset[Row]): Seq[DataFrame] = {
+    val labelColOpt = if (isSet(labelColumnName)) {
+      Some(data($(labelColumnName)))
```
Comment (tovbinm) [inline core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataBalancer.scala]: please use `Option` instead of `Some` (the worst thing is to have `Some(null)`

File: core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala [hunk 17]
```diff
@@ -75,40 +78,91 @@ class DataCutter(uid: String = UID[DataCutter]) extends Splitter(uid = uid) with
...
-    import data.sparkSession.implicits._
+    log.info(s"Dropping rows with columns not in $labelSet")
 
-    val labels = data.map(r => r.getDouble(0) -> 1L)
-    val labelCounts = labels.groupBy(labels.columns(0)).sum(labels.columns(1)).persist()
-    val (resKeep, resDrop) = estimate(labelCounts)
-    labelCounts.unpersist()
-    setLabels(resKeep, resDrop)
+    // Update metadata that spark.ml Classifier is using tp determine the number of classes
+    //
```
Comment (tovbinm) [inline core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala]: remove extra line

File: core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala [hunk 18]
```diff
@@ -75,40 +78,91 @@ class DataCutter(uid: String = UID[DataCutter]) extends Splitter(uid = uid) with
...
+        }
+
+      na.withValues(newLabelMetaArr)
+    }
 
-    summary = Option(DataCutterSummary(labelsKept = getLabelsToKeep, labelsDropped = getLabelsToDrop))
-    summary
+    // filter low cardinality labels out of the dataframe to reduce the volume and  to keep
+    // it in sync with the new metadata.
+    //
```
Comment (tovbinm) [inline core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala]: remove extra line as well

File: core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala [hunk 19]
```diff
@@ -75,40 +78,91 @@ class DataCutter(uid: String = UID[DataCutter]) extends Splitter(uid = uid) with
...
+    val dataPrep = data
+      .filter(r => labelSet.contains(r.getDouble(labelColIdx)))
+      .withColumn(labelColName, data(labelColName).as("_", metadataNA.toMetadata))
```
Comment (tovbinm) [inline core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala]: what is this magical `"_"` underscore column? ;)

File: core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala (hunk 4 above)
Comment (tovbinm) [reply core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala]: you can reach it by creating an object in the same namespace. please do so, since you are accessing the same const values numerous times in this code.

File: core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala (hunk 15 above)
Comment (tovbinm) [reply core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala]: it's not really a user friendly message either. please provide some more valuable information.

File: core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala [hunk 20]
```diff
@@ -174,18 +242,39 @@ private[impl] trait DataCutterParams extends Params {
...
   private[op] def getLabelsToDrop: Array[Double] = $(labelsToDrop)
 
+  private[op] final val labelsDroppedTotal = new LongParam(this, "labelsDroppedTotal",
+    "the number of labels dropped")
+
+  private[op] def getLabelsDroppedTotal: Long = $(labelsDroppedTotal)
+
+  final val maxLabelsDroppedForDiagnostics = new IntParam(this, "maxLabelsDroppedForDiagnostics",
+    "maximum number of dropped label categories to retain for logging",
+    ParamValidators.inRange(lowerBound = 0, upperBound = 100, lowerInclusive = true, upperInclusive = true)
```
Comment (tovbinm) [inline core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala]: is there a reason why do we set 100 as an upper limit?

File: core/src/main/scala/com/salesforce/op/stages/impl/tuning/Splitter.scala [hunk 21]
```diff
@@ -82,12 +79,23 @@ abstract class Splitter(val uid: String) extends SplitterParams {
...
   protected def checkPreconditions(): Unit =
     require(summary.nonEmpty, "Cannot call validationPrepare until preValidationPrepare has been called")
 
+  /**
+    * Add a splitter parameter to name the label column
+    * @param label
+    * @return
+    */
+  def withLabelColumnName(label: String): Splitter = {
+    if (!isSet(labelColumnName)) {
```
Comment (tovbinm) [inline core/src/main/scala/com/salesforce/op/stages/impl/tuning/Splitter.scala]: so there is not way to override the label column once it's set? why limit it?

File: core/src/test/scala/com/salesforce/op/stages/impl/classification/MultiClassificationModelSelectorTest.scala [hunk 22]
```diff
@@ -311,9 +327,90 @@ class MultiClassificationModelSelectorTest extends FlatSpec with TestSparkContex
...
     fitted.modelStageIn.parent.extractParamMap().toSeq
-      .collect{ case p: ParamPair[_] if p.param.name == "impurity" => p.value }.head shouldBe myParam
+      .collect { case p: ParamPair[_] if p.param.name == "impurity" => p.value }.head shouldBe myParam
 
     val meta = ModelSelectorSummary.fromMetadata(fitted.getMetadata().getSummaryMetadata())
     meta.validationResults.head shouldBe myMetadata
   }
+
+  it should "trim low-cardinality labels during cross validation" in {
+    import org.scalatest.prop.TableDrivenPropertyChecks._
```
Comment (tovbinm) [inline core/src/test/scala/com/salesforce/op/stages/impl/classification/MultiClassificationModelSelectorTest.scala]: you can simply mixin `org.scalatest.prop.PropertyChecks` into your test instead of local import

File: core/src/test/scala/com/salesforce/op/stages/impl/classification/MultiClassificationModelSelectorTest.scala [hunk 23]
```diff
@@ -311,9 +327,90 @@ class MultiClassificationModelSelectorTest extends FlatSpec with TestSparkContex
...
+          .transform(bigNoneIndexedData)
+          .select(labelColName, "features")
+          .persist()
+
+        val countDistinct = bigData.select(labelColName).distinct().count()
+        log.info(s"bigdata uniqs $countDistinct")
+        val bigDataWithMeta = if (metaDataMode == "withNumVals") {
+          val na = NominalAttribute.defaultAttr
+            .withName(labelColName) // no vals, no num_vals
+          bigData.drop("_").withColumn(labelColName, col(labelColName).as("_",
```
Comment (tovbinm) [inline core/src/test/scala/com/salesforce/op/stages/impl/classification/MultiClassificationModelSelectorTest.scala]: or here is the magical `"_"` column again

File: core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala (hunk 14 above)
Comment (leahmcguire) [reply core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala]: ok but lets make it private to OP if we just want it for testing

File: core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala (hunk 20 above)
Comment (leahmcguire) [reply core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala]: This is the number of names of dropped labels that you keep? can we change the name to reflect that? maybe maxNamesForDroppedLabels

File: core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala (hunk 18 above)
Comment (gerashegalov) [reply core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala]: sure , coding conventions from past employers are sneaking in

File: core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala (hunk 19 above)
Comment (gerashegalov) [reply core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala]: magic of avoiding using labelColName 3 times on the same line :)

File: core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala (hunk 4 above)
Comment (gerashegalov) [reply core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala]: too pragmatic to my taste but I don't mind

File: core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala (hunk 20 above)
Comment (gerashegalov) [reply core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala]: @tovbinm it's a reasonable limit to log. Int.MaxValue is unreasonable

File: core/src/main/scala/com/salesforce/op/stages/impl/tuning/Splitter.scala (hunk 21 above)
Comment (gerashegalov) [reply core/src/main/scala/com/salesforce/op/stages/impl/tuning/Splitter.scala]: I find it difficult to reason about the logic without making this param immutable once set.

File: core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala (hunk 20 above)
Comment (tovbinm) [reply core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala]: Look artificial to me and should perhaps be relative to data size. let's extend it to 1000 at least.

File: core/src/main/scala/com/salesforce/op/stages/impl/tuning/Splitter.scala (hunk 21 above)
Comment (tovbinm) [reply core/src/main/scala/com/salesforce/op/stages/impl/tuning/Splitter.scala]: I think this will bite us in the future.

File: core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala (hunk 20 above)
Comment (gerashegalov) [reply core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala]: anything proportional to data size will have the effect of creating huge un-GC'able  collections in degenerate cases, thus a hard cap on top of it is also necessary. Less of a concern if we just pipe it to logging instead of storing it in a param.

File: core/src/main/scala/com/salesforce/op/stages/impl/tuning/Splitter.scala (hunk 21 above)
Comment (gerashegalov) [reply core/src/main/scala/com/salesforce/op/stages/impl/tuning/Splitter.scala]: No doubt, but I think it will bite us unpredictably if we make it mutable. I can add a warning log instead of silently refusing to modify it.

**Comment by tovbinm** [comment]
🎆 🍾
